openapi: 3.0.0
info:
  title: Follow Up Boss API
  version: 1.0.0
  description: API in Follow Up Boss
servers:
  - url: https://api.followupboss.com
paths:
  # public-endpoint.yml
  /public-endpoint:
    $ref: './contracts/public-endpoint.yml#/paths/public-endpoint'
  # internal-endpoint.yml
  /internal-endpoint:
    $ref: './contracts/internal-endpoint.yml#/paths/internal-endpoint'
  # mixed-endpoint.yml
  /mixed-endpoint:
    $ref: './contracts/mixed-endpoint.yml#/paths/mixed-endpoint'
